version: 0.2

env:
  secrets-manager:
    REACT_APP_BASE_URL: 'deok-map-env:REACT_APP_BASE_URL'
    REACT_APP_MAP_KEY: 'deok-map-env:REACT_APP_MAP_KEY'
    REACT_APP_REST_API_KEY: 'deok-map-env:REACT_APP_REST_API_KEY'

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing dependencies...
      - node -v
      - npm i
  build:
    commands:
      - echo Building the project...
      - npm run build
      - aws s3 sync build/ s3://$BUCKET_NAME
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /*
